@startuml
!include Style.puml
group sd AddStudentCommand
participant ":AddStudentCommand" as C LOGIC_COLOR_3
participant ":AppState" as A LOGIC_COLOR_2
participant ":CommandResult" as R LOGIC_COLOR_8

[-> C: execute(appState, arguments)

opt matricNumber or name is null
[<--C : throw IllegalValueException
end

C -> A : addStudent(matricNumber, name)
activate A
C <-- A
deactivate A
create R
C -> R : new CommandResult
activate R
C <-- R : CommandResult
deactivate R

[<-- C : CommandResult
end
@enduml