@startuml
!include Style.puml
group sd DeleteStudentCommand
participant ":DeleteStudentCommand" as C LOGIC_COLOR_3
participant ":AppState" as A LOGIC_COLOR_2
participant ":CommandResult" as R LOGIC_COLOR_8

[-> C

opt matricNumber is null
[<--C : IllegalValueException
end

C -> A : deleteStudent(matricNumber)
activate A
alt student found and deleted
C <-- A
else student not found
C <-- A : StudentNotFoundException
[<-- C : StudentNotFoundException
end
deactivate A

C -> A : deleteGradesByMatricNumber(matricNumber)
activate A
C <-- A
deactivate A

create R
C -> R : new CommandResult
activate R
C <-- R : CommandResult
deactivate R

[<-- C : CommandResult
end
@enduml