@startuml
!include Style.puml
group sd FindStudentCommand
participant ":FindStudentCommand" as C LOGIC_COLOR_3
participant ":AppState" as A LOGIC_COLOR_2
participant ":HashMap<String, String>" as H LOGIC_COLOR_7
participant ":CommandResult" as R LOGIC_COLOR_8

[-> C
C -> H : get("i/")
activate H
C <-- H : matricNumber
deactivate H
C -> H : get("n/")
activate H
C <-- H : name
deactivate H

opt matricNumber and name are null
[<--C : throw IllegalValueException
end

alt matricNumber not null
C -> A : findStudentByMatricNumber(matricNumber)
activate A
C <-- A : StudentList
deactivate A
else
C -> A : findStudentByName(name)
activate A
C <-- A : StudentList
deactivate A
end

deactivate A
create R
C -> R : new CommandResult
activate R
C <-- R : CommandResult
deactivate R

[<-- C : CommandResult
end
@enduml