@startuml

!include Style.puml
participant ":TutorLink" as TL LOGIC_COLOR_5
participant "gradeStorage: GradeStorage" as GS LOGIC_COLOR_4
participant "grades: ArrayList<Grade>" as AL LOGIC_COLOR_6
participant "fileScanner: Scanner" as FS LOGIC_COLOR_7

create GS
TL -> GS: new GradeStorage(GRADE_FILE_PATH, initialComponentList, initialStudentList)
activate GS
TL <-- GS: gradeStorage: GradeStorage
deactivate GS

TL -> GS: loadGradeList()
activate GS

create AL
GS -> AL: new ArrayList<Grade>()
activate AL
GS <-- AL: grades: Grade
deactivate AL

create FS
GS -> FS: new Scanner(path: String)
activate FS
GS <-- FS: fileScanner: Scanner
deactivate FS

loop fileScanner.hasNext()
    GS -> FS: nextLine()
    activate FS
    GS <-- FS: currentLine: String
    deactivate FS
    GS -> GS: getGradeFromFileLine(currentLine: String)
    activate GS
    GS --> GS: newGrade: Grade
    deactivate GS

    alt success
        GS -> AL: add(newGrade)
        activate AL
        GS <-- AL
        deactivate AL
    else InvalidDataFileLineException
    end

end

destroy FS

TL <-- GS: grades: Grade
deactivate GS

@enduml
