@startuml
!include Style.puml
participant ":TutorLink" as TL LOGIC_COLOR_5
participant ":Ui" as UI LOGIC_COLOR_6
participant ":AppState" as A LOGIC_COLOR_2
participant "studentStorage:Storage" as SS LOGIC_COLOR_4
participant "componentStorage:Storage" as CS LOGIC_COLOR_4
participant "gradeStorage:Storage" as GS LOGIC_COLOR_4

group sd setup
[->TL : main()
activate TL
TL->UI: displayWelcomeMessage()
activate UI
TL <-- UI
deactivate UI

alt setup success
    create SS
    TL -> SS : new StudentStorage
    activate SS
    TL <-- SS : StudentStorage
    deactivate SS

    create CS
    TL -> CS : new ComponentStorage
    activate CS
    TL <-- CS :ComponentStorage
    deactivate CS

    create GS
    TL -> GS : new ComponentStorage
    activate GS
    TL <-- GS :ComponentStorage
    deactivate GS

    TL -> SS : loadStudentList()
    activate SS
    TL <-- SS : ArrayList<Student>
    deactivate SS

    TL -> CS : loadComponentList()
    activate CS
    TL <-- CS : ArrayList<Component>
    deactivate CS

    TL -> GS : loadGradeList()
    activate GS
    TL <-- GS : ArrayList<Grade>
    deactivate GS

    create A
    TL -> A : new AppState(ArrayList<Student>, ArrayList<Component>, ArrayList<Grade>)
    activate A
    TL <-- A : appState
    deactivate A
else TutorLinkException
        TL -> UI : displayException(exception)
        activate UI
        TL <-- UI
        deactivate UI
end

deactivate UI
[<-- TL
deactivate TL
end
@enduml